import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({ children }) => (
    <html lang="en">
        <body>
            <AntdRegistry>{children}</AntdRegistry>
        </body>
    </html>
);

export default RootLayout;