import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { SpeedInsights } from '@vercel/speed-insights/next';
import Head from "next/head";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({ children }) => (
    <html lang="en">
        <Head>
            <link rel="manifest" href="/manifest.json" />
            <meta name="theme-color" content="#000000" />
        </Head>
        <body>
            <AntdRegistry>{children}</AntdRegistry>
            <SpeedInsights />
        </body>
    </html>
);

export default RootLayout;